name: Android CI

# Trigger the workflow when pushing on master - (master will be only updated by Pull Requests.)
on:
  push:
    branches:
      - feature/sem-ver

jobs:
  build:
    name: Release Android apk on master merge.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setting Github Username and email from last commit
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

      - name: Grant Permission to Execute
        run: chmod +x gradlew

#      - name: Build & Test Project
#        run: ./gradlew assemble

      - name: Uploading Patch Build to playstore.
        if: "contains(github.event.head_commit.message, 'Release Patch Build')"
        run: |
          ./gradlew getPatchVersion > ${{ github.workspace }}/qa-notes.txt
          echo ${{ steps.vars.outputs.going_version_name }}
          ./gradlew bumpPatchVersion
          git add .
          git commit -m " ${{ steps.vars.outputs.going_version_name }} Patch Version Bumped"
          git push

      - name: Uploading Minor Build to playstore.
        if: "contains(github.event.head_commit.message, 'Release Minor Build')"
        run: |
          echo "::set-output name=going_version_name::$(./gradlew getMinorVersion)\n"
          echo ${{ steps.vars.outputs.going_version_name }}
          ./gradlew bumpMinorVersion
           git add .
           git commit -m " ${{ steps.vars.outputs.going_version_name }} Minor Version Bumped"
           git push

      - name: Uploading Major Build to playstore.
        if: "contains(github.event.head_commit.message, 'Release Major Build')"
        run: |
          echo "::set-output name=going_version_name::$(./gradlew getMajorVersion)\n"
          echo ${{ steps.vars.outputs.going_version_name }}
          ./gradlew bumpMajorVersion
           git add .
           git commit -m " ${{ steps.vars.outputs.going_version_name }} Major Version Bumped"
           git push

#      - name: Build & Test Project
#        run: ./gradlew assemble
#
#      - name: Build debug APK
#        run: bash ./gradlew assembleDebug --stacktrace #build apk according to you
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v2-preview
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk