name: Android CI

# Trigger the workflow when pushing on master - (master will be only updated by Pull Requests.)
on:
  push:
    branches:
      - feature/sem-ver

jobs:
  build:
    name: Run Unit Test and Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Updating Patch Build Version
        if: "contains(github.event.head_commit.message, 'Release Patch Build')"
        run: ./gradlew bumpPatchVersion

      - name: Updating Patch Build Version
        if: "contains(github.event.head_commit.message, 'Release Minor Build')"
        run: ./gradlew bumpMinorVersion

      - name: Updating Patch Build Version
        if: "contains(github.event.head_commit.message, 'Release Major Build')"
        run: ./gradlew bumpMajorVersion

      - name: Build & Test Project
        run: ./gradlew assemble

      - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace #build apk according to you

      - name: Upload APK
        uses: actions/upload-artifact@v2-preview
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk