name: Android CI

# Trigger the workflow when pushing on master - (master will be only updated by Pull Requests.)
on:
  push:
    branches:
      - feature/sem-ver

jobs:
  build:
    name: Release Android apk on master merge.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setting Github Username and email from last commit
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      #      - name: Build & Test Project
      #        run: ./gradlew assemble

      - name: Bumping Patch Version
        if: "contains(github.event.head_commit.message, '[release-patch]')"
        run: |
          ./gradlew getPatchVersion
          ./gradlew bumpPatchVersion

      - name: Bumping Minor Version.
        if: "contains(github.event.head_commit.message, '[release-minor]')"
        run: |
          ./gradlew getMinorVersion
          ./gradlew bumpMinorVersion

      - name: Bumping Major Version.
        if: "contains(github.event.head_commit.message, '[release-major]')"
        run: |
          ./gradlew getMajorVersion
          ./gradlew bumpMajorVersion

      - uses: pCYSl5EDgo/cat@master
        id: releasing_version
        with:
          path: ${{ github.workspace }}/temp.txt

      - uses: pCYSl5EDgo/cat@master
        id: releasing_notes
        with:
          path: ${{ github.workspace }}/release-notes.txt


      - name: Build Released ${{ steps.releasing_version.outputs.text }} Version to playstore.
        run: |
          git add .
          git commit -m " ${{ steps.releasing_version.outputs.text }} Version Bumped"
          git push
          git tag -a ${{ steps.releasing_version.outputs.text }} -m "${{ steps.releasing_version.outputs.text }}"
          git push --tags origin feature/sem-ver

#      - name: Build & Test Project
#        run: ./gradlew assemble
#
#      - name: Build debug APK
#        run: bash ./gradlew assembleDebug --stacktrace #build apk according to you
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v2-preview
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk